### ISSUE TITLE
pyronn

### ISSUE THREAD

**Issue by springXIACJ** [mareikethies/moco_diff_likelihood#1]
Hello, When I run motion_compensation.py, it tells me "ModuleNotFoundError: No module named 'pyronn. ct_reconstruction. geometry. geometry' ", however, I have installed pyronn,and I didn't find pyronn.ct_reconstruction.geometry.geometry in the pyronn source code.

**Comment by mareikethies** [comment]
Hi, 
you are right, the installation of PyroNN is not clearly described. You probably installed it from [here](https://github.com/csyben/PYRO-NN/tree/master) or using `pip install pyronn`, no? 
As a workaround, could you please try installing it from [here](https://github.com/sypsyp97/Trainable-Fourier-Series/tree/main/pyronn) instead? I would use the wheel files for your system which can be found in the "wheel" folder. Please let me know if that solves your problem. If so, I will add a reference to the readme.

**Comment by springXIACJ** [comment]
Hi，
I tried installing from [here](https://github.com/sypsyp97/Trainable-Fourier-Series/tree/main/pyronn) in Linux,  however, when I followed his instructions to install it, I got the error "ERROR: pyronn-031-cp311-cuda118-torch210-linux_x86_64.whl is not a valid wheel filename." When I followed his instructions for ”Build by yourself on HPC“, it still didn't work.

**Comment by mareikethies** [comment]
Hi, 
sorry about this. I have now added the exact version of pyronn which was used for this project to this repository. You should be able to install it from the provided sources by running the two commands mentioned in the updated readme (section Dependencies and licenses). Unfortunately, I have noticed that this likely requires a pytorch version < 2.0. I hope this solves the problem.
